# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-17 05:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='cover',
            field=models.ImageField(blank=True, upload_to='covers'),
        ),
        migrations.AlterField(
            model_name='content',
            name='actors',
            field=models.ManyToManyField(blank=True, to='catalogue.Actor'),
        ),
        migrations.AlterField(
            model_name='content',
            name='content_file',
            field=models.FileField(blank=True, upload_to='content'),
        ),
        migrations.AlterField(
            model_name='content',
            name='score',
            field=models.FloatField(default=5),
        ),
    ]
