# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-13 16:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0003_auto_20170606_2032'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='genero')),
            ],
            options={
                'verbose_name': 'genero',
                'verbose_name_plural': 'generos',
            },
        ),
        migrations.RemoveField(
            model_name='content',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.AddField(
            model_name='content',
            name='genre',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='catalogue.Genre', verbose_name='Genero'),
            preserve_default=False,
        ),
    ]
