# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-13 16:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0004_auto_20170613_1105'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='description',
            field=models.CharField(default=7, max_length=250, verbose_name='Descripcion'),
            preserve_default=False,
        ),
    ]
