# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-14 01:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0005_content_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='cover',
            field=models.ImageField(upload_to='covers', verbose_name='Portada'),
        ),
    ]
