# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-15 05:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0007_auto_20170614_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='genero'),
        ),
    ]
