# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-17 05:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercard',
            name='cvv',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='usercard',
            name='number',
            field=models.PositiveIntegerField(),
        ),
    ]
