# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-21 23:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofiles', '0002_auto_20170521_1727'),
    ]

    operations = [
        migrations.RenameField(
            model_name='creditcard',
            old_name='cvv',
            new_name='CVV',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, default='/media/avatars/default_app_avatar.png', upload_to='avatars'),
        ),
    ]
