# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-20 03:32
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofiles', '0003_userprofile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercard',
            name='cvv',
            field=models.CharField(max_length=4, validators=[django.core.validators.RegexValidator('^\\d{1,10}$')]),
        ),
        migrations.AlterField(
            model_name='usercard',
            name='number',
            field=models.CharField(max_length=19, validators=[django.core.validators.RegexValidator('^\\d{1,10}$')]),
        ),
    ]
