# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-21 23:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userprofiles', '0003_auto_20170521_1816'),
    ]

    operations = [
        migrations.RenameField(
            model_name='history',
            old_name='user',
            new_name='user_profile',
        ),
        migrations.RemoveField(
            model_name='creditcard',
            name='user',
        ),
        migrations.AddField(
            model_name='creditcard',
            name='user_profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='userprofiles.UserProfile'),
            preserve_default=False,
        ),
    ]
