# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-21 23:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofiles', '0004_auto_20170521_1822'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creditcard',
            name='due_date',
        ),
        migrations.AddField(
            model_name='creditcard',
            name='due_month',
            field=models.CharField(default=1, max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='creditcard',
            name='due_year',
            field=models.CharField(default=1, max_length=2),
            preserve_default=False,
        ),
    ]
