# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-20 23:34
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0002_auto_20170517_0024'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('userprofiles', '0004_auto_20170519_2232'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveIntegerField(blank=True)),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogue.Content')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='usercontent',
            name='content',
        ),
        migrations.RemoveField(
            model_name='usercontent',
            name='user',
        ),
        migrations.RemoveField(
            model_name='userfavorites',
            name='content',
        ),
        migrations.RemoveField(
            model_name='userfavorites',
            name='user',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='favorites',
            field=models.ManyToManyField(to='catalogue.Content'),
        ),
        migrations.DeleteModel(
            name='UserContent',
        ),
        migrations.DeleteModel(
            name='UserFavorites',
        ),
    ]
