# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-22 00:19
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofiles', '0005_auto_20170521_1842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditcard',
            name='due_month',
            field=models.CharField(choices=[('01', '01'), ('02', '02'), ('03', '03'), ('04', '04'), ('05', '05'), ('06', '06'), ('07', '07'), ('08', '08'), ('09', '09'), ('10', '10'), ('11', '11'), ('12', '12')], max_length=2),
        ),
        migrations.AlterField(
            model_name='creditcard',
            name='due_year',
            field=models.CharField(choices=[('17', '17'), ('18', '18'), ('19', '19'), ('20', '20'), ('21', '21'), ('22', '22'), ('23', '23'), ('24', '24'), ('25', '25'), ('26', '26'), ('27', '27'), ('28', '28'), ('29', '29'), ('30', '30'), ('31', '31'), ('32', '32'), ('33', '33'), ('34', '34'), ('35', '35'), ('36', '36'), ('37', '37'), ('38', '38'), ('39', '39'), ('40', '40'), ('41', '41'), ('42', '42'), ('43', '43'), ('44', '44')], max_length=2),
        ),
        migrations.AlterField(
            model_name='creditcard',
            name='number',
            field=models.CharField(max_length=19, validators=[django.core.validators.RegexValidator('^\\d{1,19}$')]),
        ),
    ]
