# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-06 03:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofiles', '0007_auto_20170603_1840'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creditcard',
            name='user_profile',
        ),
    ]
