# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-06 03:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userprofiles', '0008_remove_creditcard_user_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditcard',
            name='user_profile',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='userprofiles.UserProfile'),
            preserve_default=False,
        ),
    ]
