# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-06 03:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofiles', '0009_creditcard_user_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, default='/avatars/default_app_avatar.png', upload_to='avatars'),
        ),
    ]
