# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-14 22:27
from __future__ import unicode_literals

from django.db import migrations, models
import userprofiles.models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofiles', '0012_auto_20170614_1648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, default='avatars/default_app_avatar.png', max_length=250, upload_to=userprofiles.models.get_upload_path),
        ),
    ]
